# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  name: 'on-premise'

variables:
  imageName: 'pmarishad'
  tag: 'pilot'

# Building the Docker image
steps:
- script: hostname
- script: whoami
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: '$(imageName)/nodeimage'
    command: build
    Dockerfile: app/Dockerfile
    tags: '$(tag)'

# # Login to the Docker Registry
# - task: Docker@2
#   displayName: DockerHub login
#   inputs:
#     containerRegistry: 'DockerHub'
#     command: 'login'
# # - script: '/usr/bin/docker images --list'

# # Pushing the image to Docker Registry
# - task: Docker@2
#   displayName: Pushing Docker Image to DockerHub
#   inputs:
#     containerRegistry: 'DockerHub'
#     repository: '$(imageName)/nodeimage'
#     command: 'push'
#     tags: '$(tag)'

# # Pushing the image to ECR
# - task: ECRPushImage@1
#   displayName: Pushing Docker Image to AWS ECR
#   inputs:
#     awsCredentials: 'AwsECR'
#     regionName: 'ap-south-1'
#     imageSource: 'imagename'
#     sourceImageName: '$(imageName)/nodeimage'
#     sourceImageTag: '$(tag)'
#     repositoryName: 'pmarishad'
#     pushTag: '$(tag)'