# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- feature/*

resources:
  - repo: self

# Define Variables From Variable Group
variables:
  - group: ado-testing-vars

# Building the Docker image
stages:
  - stage: Dev
    displayName: Running in Dev Environment
    pool:
      vmImage: 'Ubuntu-16.04'

    jobs:
      - job: DevJob
        displayName: DevJob Running in Dev Environment
        steps:
        - task: Docker@2
          displayName: Build an image
          inputs:
            repository: $(image_name)
            command: build
            Dockerfile: app/Dockerfile
            tags: $(image_tag)

# # Pushing the image to ECR
# - task: ECRPushImage@1
#   displayName: Pushing Docker Image to AWS ECR
#   inputs:
#     awsCredentials: 'AwsECR'
#     regionName: 'ap-south-1'
#     imageSource: 'imagename'
#     sourceImageName: '$(imageName)/nodeimage'
#     sourceImageTag: '$(tag)'
#     repositoryName: 'ado-approval-test'
#     autoCreateRepository: true
