# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile
    tags: pmarishad

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    command: 'login'

- task: Docker@2
  displayName: Pushing Docker Image to DockerHub
  inputs:
    containerRegistry: 'DockerHub'
    command: 'push'
    tags: 'pmarishad'
