# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'
  tag: '1.0'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: '$(imageName)/NodeImage'
    command: build
    Dockerfile: app/Dockerfile
    tags: '$(tag)'

- task: Docker@2
  displayName: DockerHub login
  inputs:
    containerRegistry: 'DockerHub'
    command: 'login'
# - script: '/usr/bin/docker images --list'

- task: Docker@2
  displayName: Pushing Docker Image to DockerHub
  inputs:
    containerRegistry: 'DockerHub'
    repository: '$(imageName)/NodeImage'
    command: 'push'
    tags: '$(tag)'
